version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  shoppinglist-service:
    build: ../shoppinglist-service
    container_name: shoppinglist-service
    environment:
      HTTP_PORT: 8080
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/db
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  shoppinglist-ui:
    build: ../shoppinglist-ui
    container_name: shoppinglist-ui
    ports:
      - "4200:80"
    depends_on:
      - shoppinglist-service
