version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: secret
    ports:
      - "5555:5432"

  shoppinglist-service:
    image: ghcr.io/mrvxk/middleware-shoppinglist-service:latest
    container_name: shoppinglist-service
    environment:
      HTTP_PORT: 8080 # default is also 8080
      DB_URL: postgres
      DB_PORT: 5432
      DB_NAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      CORS_ORIGINS: localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  shoppinglist-ui:
    image: ghcr.io/mrvxk/middleware-shoppinglist-ui:latest
    container_name: shoppinglist-ui
    ports:
      - "4200:80"
    depends_on:
      - shoppinglist-service