name: Backend Docker Image Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'shoppinglist-infra/**'
      - 'README.md'
      - 'shoppinglist-ui/**'
  workflow_dispatch:

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./shoppinglist-service
          file: ./shoppinglist-service/Dockerfile
          push: true
          tags: ghcr.io/airbeat92/hft-middleware-shoppinglist-service:latest
          platforms: linux/amd64,linux/arm64
